# Site settings
title: eric-martin.com
email: eric@eric-martin.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://erimar77.github.io" # the base hostname & protocol for your site
twitter_username: erimar77
github_username:  erimar77

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
